package com.example.gasolinetrackproject.repository.impl;

import com.example.gasolinetrackproject.model.Company;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public class InMemoryCompanyRepository {

    public List<Company> findAllCompanies(){
        return List.of(new Company(1L, "7 Браќа"),
                new Company(2L, "AK OIL"),
                new Company(3L, "Besa Petrol"),
                new Company(4L, "Bunar Petrol"),
                new Company(5L, "CRP"),
                new Company(6L, "Dadi Kompani"),
                new Company(7L, "Eko Petrol"),
                new Company(8L, "Euro Activa"),
                new Company(9L, "Fer Petrol"),
                new Company(10L, "Gulf"),
                new Company(11L, "HitOil"),
                new Company(12L, "Jeddoil"),
                new Company(13L, "Jovan Petrol"),
                new Company(14L, "Krater"),
                new Company(15L, "LUK"),
                new Company(16L, "Lukoil"),
                new Company(17L, "Makpetrol"),
                new Company(18L, "Marija trejd"),
                new Company(19L, "Moderna"),
                new Company(20L, "NAS"),
                new Company(21L, "Okta"),
                new Company(22L, "okτΔ"),
                new Company(23L, "Peak"),
                new Company(24L, "Pin Petrol"),
                new Company(25L, "Power Patrol"),
                new Company(26L, "Prima Petrol"),
                new Company(27L, "Shell"),
                new Company(28L, "Station service+ supérette"),
                new Company(29L, "Tivoli Petrol"),
                new Company(30L, "TopPetrol"),
                new Company(31L, "Toptrade"),
                new Company(32L, "Wiena Petrol"),
                new Company(33L, "Zran Peka"),
                new Company(34L, "Авиа оил"),
                new Company(35L, "Авиа Оил"),
                new Company(36L, "Авто Петрол"),
                new Company(37L, "АЕ Petrol"),
                new Company(38L, "Алми Петрол"),
                new Company(39L, "АП Петрол"),
                new Company(40L, "Арка Петрол"),
                new Company(41L, "Бензоил"),
                new Company(42L, "БензОил"),
                new Company(43L, "Брако Петрол"),
                new Company(44L, "Бунар Петрол"),
                new Company(45L, "Буне Петрол"),
                new Company(46L, "Ваго Петрол"),
                new Company(47L, "ГамаОил"),
                new Company(48L, "ДА Петрол"),
                new Company(49L, "Дади Оил"),
                new Company(50L, "Дени Интернационал"),
                new Company(51L, "Дениз Петрол"),
                new Company(52L, "Детоил"),
                new Company(53L, "Дива Компани"),
                new Company(54L, "Диме Петрол"),
                new Company(55L, "Дома"),
                new Company(56L, "ДХМ Петрол"),
                new Company(57L, "Евро Оил"),
                new Company(58L, "Европа92"),
                new Company(59L, "Еко Трен"),
                new Company(60L, "ЕкоОил"),
                new Company(61L, "Лукoил"),
                new Company(62L, "Лукойл"),
                new Company(63L, "Лукоил 004"),
                new Company(64L, "Лукоил 2"),
                new Company(65L, "Мак Оил"),
                new Company(66L, "Мак Оил - Ново Нагоричане"),
                new Company(67L, "Макоил"),
                new Company(68L, "Макпетрол"),
                new Company(69L, "Макпетрол 025"),
                new Company(70L, "Макпетрол 027"),
                new Company(71L, "МакПетрол 033"),
                new Company(72L, "Макпетрол 040"),
                new Company(73L, "Макпетрол 094"),
                new Company(74L, "МакПетрол Добрушево"),
                new Company(75L, "Макпетрол Илинденска"),
                new Company(76L, "Макпетрол Козле"),
                new Company(77L, "Макпетрол Топпански"),
                new Company(78L, "МаријаТрејд"),
                new Company(79L, "Медио Петрол"),
                new Company(80L, "Митоил"),
                new Company(81L, "Мотоцентар"),
                new Company(82L, "Национал"),
                new Company(83L, "Нептун Петрол"),
                new Company(84L, "Никопетрол"),
                new Company(85L, "НиТ"),
                new Company(86L, "Окта"),
                new Company(87L, "Окта - Блу Петрол"),
                new Company(88L, "Памела Ойл"),
                new Company(89L, "Пего Петрол"),
                new Company(90L, "Рамески ИБМ"),
                new Company(91L, "РТ Петрол"),
                new Company(92L, "Салида"),
                new Company(93L, "Сателит 2000"),
                new Company(94L, "Стенковец"),
                new Company(95L, "Супертрејд"),
                new Company(96L, "ТритеролБенз"),
                new Company(97L, "Црна Река"),
                new Company(98L, "Црна Река Петрол"),
                new Company(99L, "Џет Оил"),
                new Company(100L, "Шимов"),
                new Company(101L, "Шливка Петрол")
                );
    }

}
